//
// Created by Sophie on 28/06/2021.
//

#include "GCClass.h"


std::vector<char*> GetGCCLassProperties() {
    static const std::vector<char*> properties{
            (char*) "VFTable",
            (char*) "References",
            (char*) "Unk2",
            (char*) "Unk3",
            (char*) "GCObjectHash",
            (char*) "TypeName",
            (char*) "FQTypeName",
            (char*) "SoundEnvironment",
            (char*) "Unk8",
            (char*) "Unk9",
            (char*) "Unk10",
            (char*) "Unk11",
            (char*) "Unk12",
            (char*) "SomeMap",
            (char*) "Unk14",
            (char*) "Unk15",
            (char*) "Unk16",
            (char*) "Unk17",
            (char*) "Unk18",
            (char*) "Unk19",
            (char*) "Unk20",
            (char*) "Unk21",
            (char*) "Unk22",
            (char*) "Unk23",
            (char*) "Unk24",
            (char*) "Unk25",
            (char*) "Unk26",
            (char*) "Unk27",
            (char*) "Unk28",
            (char*) "Unk29",
            (char*) "Unk30",
            (char*) "Unk31",
            (char*) "Unk32",
            (char*) "Unk33",
            (char*) "Unk34",
            (char*) "Unk35",
            (char*) "Unk36",
            (char*) "Unk37",
            (char*) "Unk38",
            (char*) "Unk39",
            (char*) "Unk40",
            (char*) "Unk41",
            (char*) "Unk42",
            (char*) "Unk43",
            (char*) "Unk44",
            (char*) "Unk45",
            (char*) "Unk46",
            (char*) "Unk47",
            (char*) "Unk48",
            (char*) "Unk49",
            (char*) "Unk50",
            (char*) "Unk51",
            (char*) "Unk52",
            (char*) "Unk53",
            (char*) "Unk54",
            (char*) "Unk55",
            (char*) "Unk56",
            (char*) "Unk57",
            (char*) "Unk58",
            (char*) "Unk59",
    };

    return properties;
}