//
// Created by Sophie on 27/06/2021.
//

#include "ClientEntityList.h"

std::vector<char*> GetClientEntityProperties() {
    static const std::vector<char*> properties{
            (char*) "Unk0",
            (char*) "OwnedObjectsStart",
            (char*) "OwnedObjectsEnd",
            (char*) "OwnedObjectsEnd_2",
            (char*) "Unk4",
            (char*) "Unk5",
            (char*) "Unk6",
            (char*) "Unk7",
            (char*) "Unk8",
            (char*) "Unk9",
            (char*) "Unk10",
            (char*) "Unk11",
            (char*) "Unk12",
            (char*) "Unk13",
            (char*) "Unk14",
            (char*) "Unk11",
            (char*) "Unk16",
            (char*) "Unk17",
            (char*) "Unk18",
            (char*) "Unk19",
            (char*) "SomeTimer",
            (char*) "Unk21",
            (char*) "SomeCountAddedToCounter",
            (char*) "SomeCounter",
            (char*) "Unk24",
            (char*) "Unk25",
            (char*) "Unk26",
            (char*) "Unk27",
            (char*) "Unk28",
            (char*) "Unk29",
            (char*) "Unk30",
            (char*) "ProcessedMessagesThisMove",
            (char*) "UpdateMessagesInQueue",
            (char*) "Unk33",
            (char*) "Unk34",
            (char*) "Unk35",
            (char*) "Unk36",
            (char*) "Unk37",
            (char*) "Unk38",
            (char*) "Unk39",
            (char*) "Unk40",
            (char*) "Unk41",
            (char*) "Unk42",
            (char*) "Unk43",
            (char*) "Unk44",
            (char*) "Unk45",
            (char*) "Unk46",
            (char*) "Unk47",
            (char*) "Unk48",
            (char*) "Unk49",
            (char*) "Unk50",
            (char*) "Unk51",
            (char*) "Unk52",
            (char*) "Unk53",
            (char*) "Unk54",
            (char*) "Unk55",
            (char*) "Unk56",
            (char*) "Unk57",
            (char*) "Unk58",
            (char*) "Unk59",
    };

    return properties;
}